version: "3.7"
services:
  api:
    build:
      context: .
    restart: unless-stopped
    tty: true
    container_name: api
    environment:
      APP_NAME: 'Api Boiler Plate'
    volumes:
      - ./:/var/www/app
      - /var/www/app/vendor
    ports:
      - "8090:80"
    networks:
      - api

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    expose:
      - 6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redisdata:/data
    networks:
      - api

  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api
      DB_USERNAME: api
      DB_PASSWORD: api_user
      MYSQL_ROOT_PASSWORD: api_user
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - api

networks:
  api:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
